[ConsoleVariables]
mh.logFPSPeriodSeconds = 600
mh.playerLogPeriodSeconds = 600
mh.hostServerKeepAlivePeriodSeconds = 120
mh.invalidPartsDisableEngine = 1
mh.invalidPartsLifespan = 1
mh.netPlayerLogFlushPeriodSeconds = 1200
mh.serverMessagePullPeriodSeconds = 600
mh.requestRewardsPeriodSeconds = 600
mh.busPaymentMultiplier = 8
mh.cargoPaymentMultiplier = 0.25
mh.limoPaymentMultiplier = 4
mh.taxiPaymentMultiplier = 6
mh.towPaymentMultiplier = 5
mh.policePatrolPayment = 1400
mh.policePatrolPointPayment = 2000
mh.policePatrolAreaPayment = 5000
mh.vehicleDriftExpPerSeconds = 5
mh.vehicleDriftMinAngleDegree = 25
mh.vehicleDriftTimeoutSeconds = 5
mh.refuelEVMinPercentPerSeconds = 0.1
mh.populationBonusByBus = 1
mh.populationBonusByFood = 1
mh.populationBonusByGarbage = 1
mh.populationBonusByTaxi = 1
mh.populationBonusByPatrol = 1
mh.populationPaymentBonusMax = 20.0
mh.populationPaymentBonusMultiplier = 1
mh.companyTruckProfitShare = 0.75
mh.busCompanyProfitShare = 0.75
mh.policeSpikePadDeploySeconds = 1
mh.policePatrolPointsPerArea = 20
mh.policePatrolPointsPerAreaMin = 6
mh.policePatrolAreaPerZoneMultiplierByPopulation = 4
mh.companyDepotStorageUsagePerService = 0.01
mh.aISpeederSpawnRatio = 400
mh.aISpeederSpawnRatioForPlayerPoliceSP = 100
mh.aISpeederSpawnRatioForPlayerPoliceMP = 100
mh.vehicleConditionConsumeSpeed = 0.0000416666
mh.cargoStackMaxVehicleHeight = 5600
mh.charcterPushingSpeed = 300
mh.charcterPushingSpeedSprintMultiplayer = 2
mh.winchSpeed = 6
mh.isDemo = 0
mh.winchControllerMaxDistance = 3000000
; mh.hostServerUrl="http://localhost/"
mh.webServerUrl="http://localhost/"
mh.invalidPartsDisableEngine = 0
mh.invalidPartsDisableLeaderboard = 0
mh.invalidPartsLifespan = 0 
mh.tireBumpSoundSpeedMax= 1000
mh.debugEngineIntakeFlood = 1